[[comments]]
author = "Tech Historian"
avatar = "https://secure.gravatar.com/avatar/tech1?d=identicon"
text = """
# Fascinating Computer History

These questions really highlight some important milestones in computing.
I especially liked learning about Ada Lovelace! 💻

Would love to see more questions about:
1. Early computers
2. Internet history
3. Programming language evolution
"""
