[[comments]]
author = "Math Teacher"
avatar = "https://secure.gravatar.com/avatar/math1?d=identicon"
text = """
# Great Practice Tool!

This arithmetic quiz helps students:
- Build number sense
- Practice mental math
- Gain confidence with basic operations

Keep up the good work! 📚
"""
