name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Changed to write to allow creating releases
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate data
        run: npm run generate

      - name: Build site
        run: npm run build

      - name: Handle Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if release exists and delete it
          if gh release view latest-data &>/dev/null; then
            gh release delete latest-data --yes
          fi
          
          # Create new release
          gh release create latest-data data.zip \
            --title "Latest Data Release" \
            --notes "$(cat << 'EOF'
          # Latest Data Release  

          This release contains generated sample data.

          ## Access Information

          All assets from this release can be accessed from:
          https://github.com/Kreijstal/github-pages-test/releases/download/latest-data/*

          For example, the data.zip file is available at:
          https://github.com/Kreijstal/github-pages-test/releases/download/latest-data/data.zip
          EOF
          )" \
            --latest

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
